### ISSUE TITLE
Código Dinâmico

### ISSUE THREAD

**Issue by Tsiangana** [rogerio-jose-gastao/python_way#1]
Ao invés de você criar variáveis e ficar trocando seus valores para testar condições, podes simplesmente colocar as condições dentro de funções e passar seus valores como parâmetros, assim sempre que você inicializar a função os seus valores virão sempre predefinidos.

**Comment by rogerio-jose-gastao** [comment]
Obrigado pelo conselho
________________________________
From: Tsiangana Zau ***@***.***>
Sent: Monday, January 8, 2024 15:07
To: rogerio-jose-gastao/python_way ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rogerio-jose-gastao/python_way] Código Dinâmico (Issue #1)


Ao invés de você criar variáveis e ficar trocando seus valores para testar condições, podes simplesmente colocar as condições dentro de funções e passar seus valores como parâmetros, assim sempre que você inicializar a função os seus valores virão sempre predefinidos.
